// Package migrations contains the PocketBase schema migrations for the consent backend.
//
// The collections defined here mirror the c15t 2.0.0 domain schema: subject, domain,
// consentPurpose, consentPolicy, runtimePolicyDecision, consent and auditLog.
package migrations

import (
	"github.com/pocketbase/pocketbase/core"
	m "github.com/pocketbase/pocketbase/migrations"
)

// Stable collection ids. Relation fields reference collections by id, so these are
// fixed rather than autogenerated to keep migrations deterministic and re-runnable.
const (
	idSubject               = "clxsubject00000"
	idDomain                = "clxdomain000000"
	idConsentPurpose        = "clxpurpose00000"
	idConsentPolicy         = "clxpolicy000000"
	idRuntimePolicyDecision = "clxrpdecision00"
	idConsent               = "clxconsent00000"
	idAuditLog              = "clxauditlog0000"
)

// tenantField is present on every collection: the domain model scopes all rows by tenant.
func tenantField() *core.TextField {
	return &core.TextField{Name: "tenantId", Max: 255}
}

func createdField() *core.AutodateField {
	return &core.AutodateField{Name: "createdAt", OnCreate: true}
}

func updatedField() *core.AutodateField {
	return &core.AutodateField{Name: "updatedAt", OnCreate: true, OnUpdate: true}
}

func init() {
	m.Register(up, down)
}

func up(app core.App) error {
	for _, build := range []func() *core.Collection{
		subjectCollection,
		domainCollection,
		consentPurposeCollection,
		consentPolicyCollection,
		runtimePolicyDecisionCollection,
		consentCollection,
		auditLogCollection,
	} {
		if err := app.Save(build()); err != nil {
			return err
		}
	}

	return nil
}

func down(app core.App) error {
	// Reverse creation order so relation targets outlive their referrers.
	names := []string{
		"auditLog",
		"consent",
		"runtimePolicyDecision",
		"consentPolicy",
		"consentPurpose",
		"domain",
		"subject",
	}

	for _, name := range names {
		collection, err := app.FindCollectionByNameOrId(name)
		if err != nil {
			continue // already absent
		}
		if err := app.Delete(collection); err != nil {
			return err
		}
	}

	return nil
}

func subjectCollection() *core.Collection {
	c := core.NewBaseCollection("subject", idSubject)
	c.Fields.Add(
		&core.TextField{Name: "externalId", Max: 255},
		&core.TextField{Name: "identityProvider", Max: 255},
		tenantField(),
		createdField(),
		updatedField(),
	)
	// An external identity is unique per tenant and provider, but only when set:
	// anonymous subjects carry no externalId and must not collide.
	c.Indexes = []string{
		`CREATE UNIQUE INDEX idx_subject_external ON subject (tenantId, identityProvider, externalId) WHERE externalId != ''`,
		`CREATE INDEX idx_subject_tenant ON subject (tenantId)`,
	}

	return c
}

func domainCollection() *core.Collection {
	c := core.NewBaseCollection("domain", idDomain)
	c.Fields.Add(
		&core.TextField{Name: "name", Required: true, Max: 255},
		tenantField(),
		createdField(),
		updatedField(),
	)
	c.Indexes = []string{
		`CREATE UNIQUE INDEX idx_domain_name ON domain (tenantId, name)`,
	}

	return c
}

func consentPurposeCollection() *core.Collection {
	c := core.NewBaseCollection("consentPurpose", idConsentPurpose)
	c.Fields.Add(
		&core.TextField{Name: "code", Required: true, Max: 255},
		tenantField(),
		createdField(),
		updatedField(),
	)
	c.Indexes = []string{
		`CREATE UNIQUE INDEX idx_purpose_code ON consentPurpose (tenantId, code)`,
	}

	return c
}

func consentPolicyCollection() *core.Collection {
	c := core.NewBaseCollection("consentPolicy", idConsentPolicy)
	c.Fields.Add(
		&core.TextField{Name: "version", Required: true, Max: 255},
		&core.TextField{Name: "type", Required: true, Max: 255},
		&core.TextField{Name: "hash", Max: 255},
		&core.DateField{Name: "effectiveDate", Required: true},
		&core.BoolField{Name: "isActive"},
		tenantField(),
		createdField(),
	)
	c.Indexes = []string{
		`CREATE UNIQUE INDEX idx_policy_version ON consentPolicy (tenantId, type, version)`,
		`CREATE UNIQUE INDEX idx_policy_active ON consentPolicy (tenantId, type) WHERE isActive = true`,
	}

	return c
}

func runtimePolicyDecisionCollection() *core.Collection {
	c := core.NewBaseCollection("runtimePolicyDecision", idRuntimePolicyDecision)
	c.Fields.Add(
		&core.RelationField{
			Name:         "policy",
			CollectionId: idConsentPolicy,
			Required:     true,
			MaxSelect:    1,
		},
		&core.TextField{Name: "fingerprint", Required: true, Max: 128},
		&core.TextField{Name: "matchedBy", Required: true, Max: 32},
		&core.TextField{Name: "countryCode", Max: 8},
		&core.TextField{Name: "regionCode", Max: 16},
		&core.TextField{Name: "jurisdiction", Required: true, Max: 32},
		&core.TextField{Name: "language", Max: 32},
		&core.TextField{Name: "model", Required: true, Max: 16},
		&core.JSONField{Name: "policyI18n", MaxSize: 65536},
		&core.TextField{Name: "uiMode", Max: 16},
		&core.JSONField{Name: "bannerUi", MaxSize: 65536},
		&core.JSONField{Name: "dialogUi", MaxSize: 65536},
		&core.JSONField{Name: "categories", MaxSize: 65536},
		&core.JSONField{Name: "preselectedCategories", MaxSize: 65536},
		&core.JSONField{Name: "proofConfig", MaxSize: 65536},
		// dedupeKey collapses identical decisions to a single row instead of one
		// per request. The unique index is what makes the upsert-on-write work.
		&core.TextField{Name: "dedupeKey", Required: true, Max: 255},
		tenantField(),
		createdField(),
	)
	c.Indexes = []string{
		`CREATE UNIQUE INDEX idx_rpd_dedupe ON runtimePolicyDecision (dedupeKey)`,
		`CREATE INDEX idx_rpd_fingerprint ON runtimePolicyDecision (tenantId, fingerprint)`,
	}

	return c
}

func consentCollection() *core.Collection {
	c := core.NewBaseCollection("consent", idConsent)
	c.Fields.Add(
		&core.RelationField{
			Name:         "subject",
			CollectionId: idSubject,
			Required:     true,
			MaxSelect:    1,
		},
		&core.RelationField{
			Name:         "domain",
			CollectionId: idDomain,
			Required:     true,
			MaxSelect:    1,
		},
		&core.RelationField{
			Name:         "policy",
			CollectionId: idConsentPolicy,
			MaxSelect:    1,
		},
		&core.RelationField{
			Name:         "runtimePolicyDecision",
			CollectionId: idRuntimePolicyDecision,
			MaxSelect:    1,
		},
		// Purpose ids are stored as a relation set rather than an opaque JSON array
		// so PocketBase can expand them and enforce referential integrity.
		&core.RelationField{
			Name:         "purposes",
			CollectionId: idConsentPurpose,
			MaxSelect:    999,
		},
		&core.JSONField{Name: "metadata", MaxSize: 65536},
		// Masked before storage: IPv4 to /24, IPv6 to /48.
		&core.TextField{Name: "ipAddress", Max: 64},
		&core.TextField{Name: "userAgent", Max: 1024},
		&core.DateField{Name: "givenAt"},
		// Derived from the resolved policy's expiryDays; empty means no expiry.
		&core.DateField{Name: "validUntil"},
		&core.TextField{Name: "jurisdiction", Max: 32},
		&core.TextField{Name: "jurisdictionModel", Max: 16},
		&core.TextField{Name: "tcString", Max: 4096},
		&core.TextField{Name: "uiSource", Max: 32},
		&core.TextField{Name: "consentAction", Max: 32},
		&core.TextField{Name: "runtimePolicySource", Max: 64},
		tenantField(),
		createdField(),
	)
	c.Indexes = []string{
		`CREATE INDEX idx_consent_subject ON consent (tenantId, subject, givenAt)`,
		`CREATE INDEX idx_consent_domain ON consent (tenantId, domain, givenAt)`,
		`CREATE INDEX idx_consent_valid ON consent (tenantId, validUntil)`,
	}

	return c
}

func auditLogCollection() *core.Collection {
	c := core.NewBaseCollection("auditLog", idAuditLog)
	c.Fields.Add(
		&core.TextField{Name: "entityType", Required: true, Max: 64},
		&core.TextField{Name: "entityId", Required: true, Max: 255},
		&core.TextField{Name: "actionType", Required: true, Max: 64},
		&core.RelationField{
			Name:         "subject",
			CollectionId: idSubject,
			MaxSelect:    1,
		},
		&core.TextField{Name: "ipAddress", Max: 64},
		&core.TextField{Name: "userAgent", Max: 1024},
		&core.JSONField{Name: "changes", MaxSize: 65536},
		&core.JSONField{Name: "metadata", MaxSize: 65536},
		tenantField(),
		createdField(),
	)
	c.Indexes = []string{
		`CREATE INDEX idx_audit_entity ON auditLog (tenantId, entityType, entityId)`,
		`CREATE INDEX idx_audit_subject ON auditLog (tenantId, subject, createdAt)`,
	}

	return c
}
